### ISSUE TITLE
Issue loading NetWASM.js

### ISSUE THREAD

**Issue by kwhitley** [DanRuta/jsNet#41]
First of all, GREAT work on this!  Can't wait to get off the ground with your lib given the super-thorough implementation of most industry features (VERY impressive for a JS lib in ML).

That said, I'm having an issue get the WebASM version to load (via NPM, from a node http server).  I've added a static pass-through path to the /dist folder in the node_modules, and the files appear to pass through to the browser just fine, but I get a `str.charCodeAt is not a function` error right off.

Suggestions?

Thanks!

```console
NetWASM.js:1 failed to asynchronously prepare wasm: TypeError: str.charCodeAt is not a function
shell_printErr @ NetWASM.js:1
(anonymous) @ NetWASM.js:1
Promise.catch (async)
doNativeWasm @ NetWASM.js:1
Module.asm @ NetWASM.js:1
(anonymous) @ NetWASM.js:1
splitPathRe @ NetWASM.js:1
__webpack_require__ @ bootstrap 223be6444fa9ea82d12d:54
exports.webassembly @ jsNet.js:7
(anonymous) @ sim.js:18
(anonymous) @ app.js:9909
__webpack_require__ @ bootstrap 223be6444fa9ea82d12d:54
(anonymous) @ app.js:4326
__webpack_require__ @ bootstrap 223be6444fa9ea82d12d:54
webpackJsonpCallback @ bootstrap 223be6444fa9ea82d12d:25
(anonymous) @ app.js:1
```

**Comment by DanRuta** [comment]
Hi. Thank you kindly :) It still has a long way to go.

I wasn't actually able to reproduce that error message. Are you perhaps using a special way of loading it? There was an issue (https://github.com/DanRuta/jsNet/issues/33) with loading it with parceljs, for example.

I may be wrong, but from that stack, could you be using webpack? I've never used webpack before, but this might be related (https://github.com/kripken/emscripten/issues/6170).


What I've tried is an html file using these script tags:
```html
<script src="./node_modules/jsNet/dist/jsNetWebAssembly.min.js"></script>
<script src="./node_modules/jsNet/dist/NetWASM.js"></script>
```

and the server code:
```js
const http = require("http")
const fs = require("fs")
const url = require("url")
const PORT = 1338

http.createServer((request, response) => {

    let path = url.parse(request.url).pathname
    let data

    path = (path=="/"?"/index.html":path)

    console.log(path)

    switch(path){
        case "/NetWASM.wasm":
            path = __dirname+"/node_modules/jsNet/dist"+path
            console.log("Returning the wasm file", path)
            try{
                data = fs.readFileSync(path)
            }catch(e){}
            break
        default:
            try{
                data = fs.readFileSync(__dirname+path)
            }catch(e){}
    }

    response.end(data)

}).listen(PORT, () => console.log(`Server Listening on port: ${PORT}`))

```
The `server.js` and `index.html` files in the same folder, next to the `node_modules` folder.

Let me know if this is wildly different from what you have

**Comment by DanRuta** [comment]
If you've still got issues with this file, you can check out the newly added examples folder, in the v3.3.0 release, which has the set-up that I use for development.

It needs to be served via the `server.js` file.

**Comment by kwhitley** [comment]
Sorry for the delayed response!  I've been busy playing with your lib, and testing it out...

So regarding this, I've tried both your specific-route approach (match the route, serve the file), as well as setting a static path via `express.static('pathnamehere')` to your `dist/` folder within the node_modules.  This allows *all* files within your dist to be reachable (e.g. http://localhost:3000/NetWASM.js).  Regardless, I still get the above error in NetWASM.js (I assume when trying to load the .wasm file).  I've verified that the .wasm file is being served (I assume correctly), and when trying to reference it directly, it gives me a download dialog.

In the client, I'm importing like this:
```js
import jsnet from 'jsnet'

const { Module, Network, Layer, FCLayer, ConvLayer, PoolLayer, Filter, Neuron, NetMath, NetUtil } = jsnet.webassembly()
```

This works 100% when using `.js()` but fails when using `.webassembly()`

It could be that webpack is modifying your intended module definition when it crawls through to import it, but I've never seen that issue before.

Is there a way for me to test that the .wasm file is being served correctly?  Alternatively, if you exposed a global function or something, I could embed them the old fashioned way (e.g. <script> tags), then just reference in the variables as needed.  I've had to do this for libraries like neataptic, for instance (I don't love it, but it's doable).

Any help would be appreciated on this - as large networks slow down drastically each epoch (I'm not sure why, but it could be eating memory if it's preserving snapshots of previous iterations to roll-back to during validation... assuming I read the docs correctly).

All said, I love the direction this is going, the built-in validation, early stopping, regularization, dropout, etc, etc to help with the curse of overfitting (easy for the python folks, but much of that hasn't migrated to JS to yet).  I'll have a bunch of feedback for you coming up, having used it for a few days now :)

**Comment by DanRuta** [comment]
Ok, I installed Webpack and played around with it, and there was, indeed a scoping issue with the WebAssembly Module. I've made it global now (window.Module), and pushed a webpack example to the examples folder. The script part looks like this, now:

```javascript
import jsnet from "jsnet"

const { Network, Layer, FCLayer, ConvLayer, PoolLayer, Filter, Neuron, NetMath, NetUtil } = jsnet.webassembly()

window.addEventListener("jsNetWASMLoaded", () => {

    console.log("jsnet", jsnet)
    console.log("Module", Module) // this is now in the window object

    window.net = new Network({
        Module,
        layers: [2,3,4]
    })
    console.log("net", window.net)
})
```

Loading it through that seems to work for me. I assume that was the cause of your issue, despite the error message being different. I assume also that, when using the WebAssembly version, you used the "jsNetWASMLoaded" event listener, as this is needed for awaiting WebAssembly's lazy loading of the wasm file.

Let me know if the issue persists. I may need to know a bit more about your set-up, if it does, so I can play around with it locally.

As for checking if the .wasm file gets loaded, I personally see this gibberish in the response section of the request, in Chrome dev tools' Network tab.
![image](https://user-images.githubusercontent.com/12224772/37765301-c48bd1e2-2dbb-11e8-9146-2782157f7f43.png)


I greatly appreciate the feedback, by the way :). Learning this as I go along, so there's stuff to be ironed out.

**Comment by kwhitley** [comment]
Still getting this issue with 3.3.1... do I need to specifically load the dev branch or something for this?

**Comment by kwhitley** [comment]
I can confirm the .wasm is loading identically to yours btw 👍

**Comment by kwhitley** [comment]
Also, I get the following dependency error in Node, regarding your requiring "fs" in NetWASM.js

![image](https://user-images.githubusercontent.com/865416/37791031-243bdb90-2dd6-11e8-8d31-50f9bd153bd0.png)

**Comment by kwhitley** [comment]
And here's the issue in Chrome when calling `.webassembly()`

![image](https://user-images.githubusercontent.com/865416/37791074-4157147e-2dd6-11e8-9521-11298cf751dd.png)

**Comment by DanRuta** [comment]
I got the 'fs' issue as well. I don't touch the NetWASM.js file (other than adding it to the window scope). But adding the following to the webpack config seemed to fix the fs error:
```
node: {
  fs: 'empty'
}
```

I'm trying to recreate the charCodeAt error now.

In the meantime, did you try the webpack example in the `examples` folder? It should all be in the master branch.

**Comment by kwhitley** [comment]
This may help (I hope):

I added in the following line to your `/dist/NetWASM.js`, inside the function lengthBytesUTF8(str) to see what was being passed in (obviously something other than a string to be receiving that error):

```js
console.log('lengthBytesUTF8', typeof str, str)
```

And here's what it outputs... 

![image](https://user-images.githubusercontent.com/865416/37792961-4d0f61c2-2ddb-11e8-946c-9add94295935.png)

Obviously it's being passed a variety of things... a string, the Window object (probably a "this"), a fetch/promise, etc

My guess is definitely a scoping/context issue of the module... but seeing the whole thing as a minified 1-liner, it's difficult to track down!

**Comment by kwhitley** [comment]
Ok, I think it was one of my loaders or resolvers in webpack (for SASS compilation, React, JSX, etc)... I commented out my entire config and have been adding it back piece by piece.  The errors are cleared for the moment.

Crossing my fingers!

Also thanks for the quick fix for the fs issue - worked for me! 👍

**Comment by DanRuta** [comment]
Oh, that's great to know. I wish wasm played a bit more nicely with everything else, but maybe in due time.

**Comment by kwhitley** [comment]
Looks like the culprit was in my polyfill loader for "fetch" (legacy inclusion for IE support)

![image](https://user-images.githubusercontent.com/865416/37793428-a9be9bbc-2ddc-11e8-921c-cdb62f99551b.png)

🤦‍♂️ 

Thanks so much for helping me solve this - now I should be able to iterate through experiments with the library a lot faster!

**Comment by kwhitley** [comment]
Gonna mark this as closed... and MAN is the webassembly version fast.  Unbelievably so!
