### ISSUE TITLE
Question: Normalization & Weight Initialization

### ISSUE THREAD

**Issue by kwhitley** [DanRuta/jsNet#46]
So as most of my data is z-score normalized:

```
(value - mean) / stddev
```

It centers around zero, with the occasional value > 1 or < -1.

Is this a problem with your architecture?  Do I need to specifically initialize weights to zero-centered (instead of ~0.5 for [0..1] inputs), and if so, how to do this?

Also, hypothetically, how would one deal with some inputs that are [0..1] scaled, and others that are ~[-1..1]?  Do those play nicely together or no?

Cheers, thanks!

**Comment by DanRuta** [comment]
If you need to change the centering, you can use the `mean` attribute for weights initialization, which goes with the gaussian distribution. 

As for whether it's necessary or not, it won't break if you don't. You can initialize weights however you'd like. Any configurations just help in optimizing for the particular dataset you're using.

From what I've played with in the past, however, matching the mean/range to the data worked best for good results.

You can try doing a pre-processing step of normalization if you'd like, but aside from maybe a difference in accuracy, it shouldn't matter.

If you use the sigmoid activation function, it all gets squished anyway. Typically sigmoid is ok for [0..1] , but [-1..1] might mean a low gradient from values below 0.

**Comment by kwhitley** [comment]
Ok thanks for the clarification! 👍
